import {
  Folder, Briefcase, Building2, GraduationCap, FlaskConical, ShoppingBag, Wallet,
  Plane, Car, Home, Code, Pencil, Lightbulb, Globe, BarChart3, Calendar, Sparkles,
  AlignLeft, Type, MessageSquare, Target, Zap, BookOpen, FileText, PenTool, Command,
  Cpu, Database, Layers, Mail, Map, Music, Image, Video, Mic, Calculator, Clock,
  Compass, Flag, Heart, Star, Sun, Moon, Smartphone, Monitor, Printer, Camera, Gift,
  Trophy, Award, Shield, Lock, Key, Rocket, Hammer, Wrench, Scissors, Paintbrush,
  Brush, Ruler, Clipboard, StickyNote, Bookmark, Tag, Hash, AtSign, Link, Paperclip,
  Upload, Download, Cloud, Umbrella, Thermometer, Battery, Plug, ZapOff, Flame,
  Droplets, Leaf, TreePine, Flower2, Mountain, Waves, Fish, Bird, Cat, Dog, Rabbit,
  Bug, Snail, Turtle, BugOff,
  type LucideIcon,
} from 'lucide-react'

export const PROJECT_ICONS: { name: string; icon: LucideIcon }[] = [
  { name: "Folder", icon: Folder },
  { name: "Briefcase", icon: Briefcase },
  { name: "Building2", icon: Building2 },
  { name: "GraduationCap", icon: GraduationCap },
  { name: "FlaskConical", icon: FlaskConical },
  { name: "ShoppingBag", icon: ShoppingBag },
  { name: "Wallet", icon: Wallet },
  { name: "Plane", icon: Plane },
  { name: "Car", icon: Car },
  { name: "Home", icon: Home },
  { name: "Code", icon: Code },
  { name: "Pencil", icon: Pencil },
  { name: "Lightbulb", icon: Lightbulb },
  { name: "Globe", icon: Globe },
  { name: "BarChart3", icon: BarChart3 },
  { name: "Calendar", icon: Calendar },
  { name: "Sparkles", icon: Sparkles },
  { name: "AlignLeft", icon: AlignLeft },
  { name: "Type", icon: Type },
  { name: "MessageSquare", icon: MessageSquare },
  { name: "Target", icon: Target },
  { name: "Zap", icon: Zap },
  { name: "BookOpen", icon: BookOpen },
  { name: "FileText", icon: FileText },
  { name: "PenTool", icon: PenTool },
  { name: "Command", icon: Command },
  { name: "Cpu", icon: Cpu },
  { name: "Database", icon: Database },
  { name: "Layers", icon: Layers },
  { name: "Mail", icon: Mail },
  { name: "Map", icon: Map },
  { name: "Music", icon: Music },
  { name: "Image", icon: Image },
  { name: "Video", icon: Video },
  { name: "Mic", icon: Mic },
  { name: "Calculator", icon: Calculator },
  { name: "Clock", icon: Clock },
  { name: "Compass", icon: Compass },
  { name: "Flag", icon: Flag },
  { name: "Heart", icon: Heart },
  { name: "Star", icon: Star },
  { name: "Sun", icon: Sun },
  { name: "Moon", icon: Moon },
  { name: "Smartphone", icon: Smartphone },
  { name: "Monitor", icon: Monitor },
  { name: "Printer", icon: Printer },
  { name: "Camera", icon: Camera },
  { name: "Gift", icon: Gift },
  { name: "Trophy", icon: Trophy },
  { name: "Award", icon: Award },
  { name: "Shield", icon: Shield },
  { name: "Lock", icon: Lock },
  { name: "Key", icon: Key },
  { name: "Rocket", icon: Rocket },
  { name: "Hammer", icon: Hammer },
  { name: "Wrench", icon: Wrench },
  { name: "Scissors", icon: Scissors },
  { name: "Paintbrush", icon: Paintbrush },
  { name: "Brush", icon: Brush },
  { name: "Ruler", icon: Ruler },
  { name: "Clipboard", icon: Clipboard },
  { name: "StickyNote", icon: StickyNote },
  { name: "Bookmark", icon: Bookmark },
  { name: "Tag", icon: Tag },
  { name: "Hash", icon: Hash },
  { name: "AtSign", icon: AtSign },
  { name: "Link", icon: Link },
  { name: "Paperclip", icon: Paperclip },
  { name: "Upload", icon: Upload },
  { name: "Download", icon: Download },
  { name: "Cloud", icon: Cloud },
  { name: "Umbrella", icon: Umbrella },
  { name: "Thermometer", icon: Thermometer },
  { name: "Battery", icon: Battery },
  { name: "Plug", icon: Plug },
  { name: "ZapOff", icon: ZapOff },
  { name: "Flame", icon: Flame },
  { name: "Droplets", icon: Droplets },
  { name: "Leaf", icon: Leaf },
  { name: "TreePine", icon: TreePine },
  { name: "Flower2", icon: Flower2 },
  { name: "Mountain", icon: Mountain },
  { name: "Waves", icon: Waves },
  { name: "Fish", icon: Fish },
  { name: "Bird", icon: Bird },
  { name: "Cat", icon: Cat },
  { name: "Dog", icon: Dog },
  { name: "Rabbit", icon: Rabbit },
  { name: "Bug", icon: Bug },
  { name: "Snail", icon: Snail },
  { name: "Turtle", icon: Turtle },
  { name: "BugOff", icon: BugOff },
]

export const PROJECT_ICON_NAMES = PROJECT_ICONS.map(i => i.name)

export const ICON_MAP: Record<string, LucideIcon> = {}
PROJECT_ICONS.forEach(({ name, icon }) => { ICON_MAP[name] = icon })

export function getProjectIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || Folder
}

export const PROJECT_COLORS = [
  { name: "Slate", value: "#64748b", bg: "rgba(100,116,139,0.1)" },
  { name: "Red", value: "#ef4444", bg: "rgba(239,68,68,0.1)" },
  { name: "Orange", value: "#f97316", bg: "rgba(249,115,22,0.1)" },
  { name: "Amber", value: "#f59e0b", bg: "rgba(245,158,11,0.1)" },
  { name: "Green", value: "#22c55e", bg: "rgba(34,197,94,0.1)" },
  { name: "Emerald", value: "#10b981", bg: "rgba(16,185,129,0.1)" },
  { name: "Teal", value: "#14b8a6", bg: "rgba(20,184,166,0.1)" },
  { name: "Cyan", value: "#06b6d4", bg: "rgba(6,182,212,0.1)" },
  { name: "Sky", value: "#0ea5e9", bg: "rgba(14,165,233,0.1)" },
  { name: "Blue", value: "#3b82f6", bg: "rgba(59,130,246,0.1)" },
  { name: "Indigo", value: "#6366f1", bg: "rgba(99,102,241,0.1)" },
  { name: "Violet", value: "#8b5cf6", bg: "rgba(139,92,246,0.1)" },
  { name: "Purple", value: "#a855f7", bg: "rgba(168,85,247,0.1)" },
  { name: "Fuchsia", value: "#d946ef", bg: "rgba(217,70,239,0.1)" },
  { name: "Pink", value: "#ec4899", bg: "rgba(236,72,153,0.1)" },
  { name: "Rose", value: "#f43f5e", bg: "rgba(244,63,94,0.1)" },
]
